// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: message_writer.proto
#ifndef GRPC_message_5fwriter_2eproto__INCLUDED
#define GRPC_message_5fwriter_2eproto__INCLUDED

#include "message_writer.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace MessageDomain {

class MessageWriter final {
 public:
  static constexpr char const* service_full_name() {
    return "MessageDomain.MessageWriter";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status PushMessage(::grpc::ClientContext* context, const ::MessageDomain::PushMessageRequest& request, ::MessageDomain::PushMessageResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MessageDomain::PushMessageResponse>> AsyncPushMessage(::grpc::ClientContext* context, const ::MessageDomain::PushMessageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MessageDomain::PushMessageResponse>>(AsyncPushMessageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MessageDomain::PushMessageResponse>> PrepareAsyncPushMessage(::grpc::ClientContext* context, const ::MessageDomain::PushMessageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MessageDomain::PushMessageResponse>>(PrepareAsyncPushMessageRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void PushMessage(::grpc::ClientContext* context, const ::MessageDomain::PushMessageRequest* request, ::MessageDomain::PushMessageResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void PushMessage(::grpc::ClientContext* context, const ::MessageDomain::PushMessageRequest* request, ::MessageDomain::PushMessageResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::MessageDomain::PushMessageResponse>* AsyncPushMessageRaw(::grpc::ClientContext* context, const ::MessageDomain::PushMessageRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::MessageDomain::PushMessageResponse>* PrepareAsyncPushMessageRaw(::grpc::ClientContext* context, const ::MessageDomain::PushMessageRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status PushMessage(::grpc::ClientContext* context, const ::MessageDomain::PushMessageRequest& request, ::MessageDomain::PushMessageResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MessageDomain::PushMessageResponse>> AsyncPushMessage(::grpc::ClientContext* context, const ::MessageDomain::PushMessageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MessageDomain::PushMessageResponse>>(AsyncPushMessageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MessageDomain::PushMessageResponse>> PrepareAsyncPushMessage(::grpc::ClientContext* context, const ::MessageDomain::PushMessageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MessageDomain::PushMessageResponse>>(PrepareAsyncPushMessageRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void PushMessage(::grpc::ClientContext* context, const ::MessageDomain::PushMessageRequest* request, ::MessageDomain::PushMessageResponse* response, std::function<void(::grpc::Status)>) override;
      void PushMessage(::grpc::ClientContext* context, const ::MessageDomain::PushMessageRequest* request, ::MessageDomain::PushMessageResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::MessageDomain::PushMessageResponse>* AsyncPushMessageRaw(::grpc::ClientContext* context, const ::MessageDomain::PushMessageRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::MessageDomain::PushMessageResponse>* PrepareAsyncPushMessageRaw(::grpc::ClientContext* context, const ::MessageDomain::PushMessageRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_PushMessage_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status PushMessage(::grpc::ServerContext* context, const ::MessageDomain::PushMessageRequest* request, ::MessageDomain::PushMessageResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_PushMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PushMessage() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_PushMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushMessage(::grpc::ServerContext* /*context*/, const ::MessageDomain::PushMessageRequest* /*request*/, ::MessageDomain::PushMessageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPushMessage(::grpc::ServerContext* context, ::MessageDomain::PushMessageRequest* request, ::grpc::ServerAsyncResponseWriter< ::MessageDomain::PushMessageResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_PushMessage<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_PushMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_PushMessage() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::MessageDomain::PushMessageRequest, ::MessageDomain::PushMessageResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::MessageDomain::PushMessageRequest* request, ::MessageDomain::PushMessageResponse* response) { return this->PushMessage(context, request, response); }));}
    void SetMessageAllocatorFor_PushMessage(
        ::grpc::MessageAllocator< ::MessageDomain::PushMessageRequest, ::MessageDomain::PushMessageResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::MessageDomain::PushMessageRequest, ::MessageDomain::PushMessageResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_PushMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushMessage(::grpc::ServerContext* /*context*/, const ::MessageDomain::PushMessageRequest* /*request*/, ::MessageDomain::PushMessageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PushMessage(
      ::grpc::CallbackServerContext* /*context*/, const ::MessageDomain::PushMessageRequest* /*request*/, ::MessageDomain::PushMessageResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_PushMessage<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_PushMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PushMessage() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_PushMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushMessage(::grpc::ServerContext* /*context*/, const ::MessageDomain::PushMessageRequest* /*request*/, ::MessageDomain::PushMessageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_PushMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PushMessage() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_PushMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushMessage(::grpc::ServerContext* /*context*/, const ::MessageDomain::PushMessageRequest* /*request*/, ::MessageDomain::PushMessageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPushMessage(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_PushMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_PushMessage() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->PushMessage(context, request, response); }));
    }
    ~WithRawCallbackMethod_PushMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushMessage(::grpc::ServerContext* /*context*/, const ::MessageDomain::PushMessageRequest* /*request*/, ::MessageDomain::PushMessageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PushMessage(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PushMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_PushMessage() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::MessageDomain::PushMessageRequest, ::MessageDomain::PushMessageResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::MessageDomain::PushMessageRequest, ::MessageDomain::PushMessageResponse>* streamer) {
                       return this->StreamedPushMessage(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_PushMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PushMessage(::grpc::ServerContext* /*context*/, const ::MessageDomain::PushMessageRequest* /*request*/, ::MessageDomain::PushMessageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPushMessage(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::MessageDomain::PushMessageRequest,::MessageDomain::PushMessageResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_PushMessage<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_PushMessage<Service > StreamedService;
};

}  // namespace MessageDomain


#endif  // GRPC_message_5fwriter_2eproto__INCLUDED
