// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_dto.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_message_5fdto_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_message_5fdto_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "user_dto.pb.h"
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_message_5fdto_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_message_5fdto_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_message_5fdto_2eproto;
namespace message {
class MessageDTO;
struct MessageDTODefaultTypeInternal;
extern MessageDTODefaultTypeInternal _MessageDTO_default_instance_;
}  // namespace message
PROTOBUF_NAMESPACE_OPEN
template<> ::message::MessageDTO* Arena::CreateMaybeMessage<::message::MessageDTO>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace message {

enum MessageType : int {
  TEXT = 0,
  EMOJI = 1,
  MULTIMEDIA = 2,
  MessageType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  MessageType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool MessageType_IsValid(int value);
constexpr MessageType MessageType_MIN = TEXT;
constexpr MessageType MessageType_MAX = MULTIMEDIA;
constexpr int MessageType_ARRAYSIZE = MessageType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MessageType_descriptor();
template<typename T>
inline const std::string& MessageType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MessageType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MessageType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MessageType_descriptor(), enum_t_value);
}
inline bool MessageType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MessageType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MessageType>(
    MessageType_descriptor(), name, value);
}
// ===================================================================

class MessageDTO final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:message.MessageDTO) */ {
 public:
  inline MessageDTO() : MessageDTO(nullptr) {}
  ~MessageDTO() override;
  explicit constexpr MessageDTO(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MessageDTO(const MessageDTO& from);
  MessageDTO(MessageDTO&& from) noexcept
    : MessageDTO() {
    *this = ::std::move(from);
  }

  inline MessageDTO& operator=(const MessageDTO& from) {
    CopyFrom(from);
    return *this;
  }
  inline MessageDTO& operator=(MessageDTO&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MessageDTO& default_instance() {
    return *internal_default_instance();
  }
  static inline const MessageDTO* internal_default_instance() {
    return reinterpret_cast<const MessageDTO*>(
               &_MessageDTO_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MessageDTO& a, MessageDTO& b) {
    a.Swap(&b);
  }
  inline void Swap(MessageDTO* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MessageDTO* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MessageDTO* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MessageDTO>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MessageDTO& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const MessageDTO& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MessageDTO* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "message.MessageDTO";
  }
  protected:
  explicit MessageDTO(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kContentFieldNumber = 6,
    kInformationFieldNumber = 4,
    kTimestampFieldNumber = 7,
    kMessageIDFieldNumber = 1,
    kLastMessageIDFieldNumber = 2,
    kUserIDFieldNumber = 3,
    kTypeFieldNumber = 5,
  };
  // string content = 6;
  void clear_content();
  const std::string& content() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_content(ArgT0&& arg0, ArgT... args);
  std::string* mutable_content();
  PROTOBUF_NODISCARD std::string* release_content();
  void set_allocated_content(std::string* content);
  private:
  const std::string& _internal_content() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_content(const std::string& value);
  std::string* _internal_mutable_content();
  public:

  // .user.InformationDTO information = 4;
  bool has_information() const;
  private:
  bool _internal_has_information() const;
  public:
  void clear_information();
  const ::user::InformationDTO& information() const;
  PROTOBUF_NODISCARD ::user::InformationDTO* release_information();
  ::user::InformationDTO* mutable_information();
  void set_allocated_information(::user::InformationDTO* information);
  private:
  const ::user::InformationDTO& _internal_information() const;
  ::user::InformationDTO* _internal_mutable_information();
  public:
  void unsafe_arena_set_allocated_information(
      ::user::InformationDTO* information);
  ::user::InformationDTO* unsafe_arena_release_information();

  // .google.protobuf.Timestamp timestamp = 7;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& timestamp() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Timestamp* release_timestamp();
  ::PROTOBUF_NAMESPACE_ID::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& _internal_timestamp() const;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_timestamp();
  public:
  void unsafe_arena_set_allocated_timestamp(
      ::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  ::PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_timestamp();

  // uint64 messageID = 1;
  void clear_messageid();
  uint64_t messageid() const;
  void set_messageid(uint64_t value);
  private:
  uint64_t _internal_messageid() const;
  void _internal_set_messageid(uint64_t value);
  public:

  // uint64 lastMessageID = 2;
  void clear_lastmessageid();
  uint64_t lastmessageid() const;
  void set_lastmessageid(uint64_t value);
  private:
  uint64_t _internal_lastmessageid() const;
  void _internal_set_lastmessageid(uint64_t value);
  public:

  // uint64 userID = 3;
  void clear_userid();
  uint64_t userid() const;
  void set_userid(uint64_t value);
  private:
  uint64_t _internal_userid() const;
  void _internal_set_userid(uint64_t value);
  public:

  // .message.MessageType type = 5;
  void clear_type();
  ::message::MessageType type() const;
  void set_type(::message::MessageType value);
  private:
  ::message::MessageType _internal_type() const;
  void _internal_set_type(::message::MessageType value);
  public:

  // @@protoc_insertion_point(class_scope:message.MessageDTO)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr content_;
  ::user::InformationDTO* information_;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp_;
  uint64_t messageid_;
  uint64_t lastmessageid_;
  uint64_t userid_;
  int type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_5fdto_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MessageDTO

// uint64 messageID = 1;
inline void MessageDTO::clear_messageid() {
  messageid_ = uint64_t{0u};
}
inline uint64_t MessageDTO::_internal_messageid() const {
  return messageid_;
}
inline uint64_t MessageDTO::messageid() const {
  // @@protoc_insertion_point(field_get:message.MessageDTO.messageID)
  return _internal_messageid();
}
inline void MessageDTO::_internal_set_messageid(uint64_t value) {
  
  messageid_ = value;
}
inline void MessageDTO::set_messageid(uint64_t value) {
  _internal_set_messageid(value);
  // @@protoc_insertion_point(field_set:message.MessageDTO.messageID)
}

// uint64 lastMessageID = 2;
inline void MessageDTO::clear_lastmessageid() {
  lastmessageid_ = uint64_t{0u};
}
inline uint64_t MessageDTO::_internal_lastmessageid() const {
  return lastmessageid_;
}
inline uint64_t MessageDTO::lastmessageid() const {
  // @@protoc_insertion_point(field_get:message.MessageDTO.lastMessageID)
  return _internal_lastmessageid();
}
inline void MessageDTO::_internal_set_lastmessageid(uint64_t value) {
  
  lastmessageid_ = value;
}
inline void MessageDTO::set_lastmessageid(uint64_t value) {
  _internal_set_lastmessageid(value);
  // @@protoc_insertion_point(field_set:message.MessageDTO.lastMessageID)
}

// uint64 userID = 3;
inline void MessageDTO::clear_userid() {
  userid_ = uint64_t{0u};
}
inline uint64_t MessageDTO::_internal_userid() const {
  return userid_;
}
inline uint64_t MessageDTO::userid() const {
  // @@protoc_insertion_point(field_get:message.MessageDTO.userID)
  return _internal_userid();
}
inline void MessageDTO::_internal_set_userid(uint64_t value) {
  
  userid_ = value;
}
inline void MessageDTO::set_userid(uint64_t value) {
  _internal_set_userid(value);
  // @@protoc_insertion_point(field_set:message.MessageDTO.userID)
}

// .user.InformationDTO information = 4;
inline bool MessageDTO::_internal_has_information() const {
  return this != internal_default_instance() && information_ != nullptr;
}
inline bool MessageDTO::has_information() const {
  return _internal_has_information();
}
inline const ::user::InformationDTO& MessageDTO::_internal_information() const {
  const ::user::InformationDTO* p = information_;
  return p != nullptr ? *p : reinterpret_cast<const ::user::InformationDTO&>(
      ::user::_InformationDTO_default_instance_);
}
inline const ::user::InformationDTO& MessageDTO::information() const {
  // @@protoc_insertion_point(field_get:message.MessageDTO.information)
  return _internal_information();
}
inline void MessageDTO::unsafe_arena_set_allocated_information(
    ::user::InformationDTO* information) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(information_);
  }
  information_ = information;
  if (information) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:message.MessageDTO.information)
}
inline ::user::InformationDTO* MessageDTO::release_information() {
  
  ::user::InformationDTO* temp = information_;
  information_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::user::InformationDTO* MessageDTO::unsafe_arena_release_information() {
  // @@protoc_insertion_point(field_release:message.MessageDTO.information)
  
  ::user::InformationDTO* temp = information_;
  information_ = nullptr;
  return temp;
}
inline ::user::InformationDTO* MessageDTO::_internal_mutable_information() {
  
  if (information_ == nullptr) {
    auto* p = CreateMaybeMessage<::user::InformationDTO>(GetArenaForAllocation());
    information_ = p;
  }
  return information_;
}
inline ::user::InformationDTO* MessageDTO::mutable_information() {
  ::user::InformationDTO* _msg = _internal_mutable_information();
  // @@protoc_insertion_point(field_mutable:message.MessageDTO.information)
  return _msg;
}
inline void MessageDTO::set_allocated_information(::user::InformationDTO* information) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(information_);
  }
  if (information) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(information));
    if (message_arena != submessage_arena) {
      information = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, information, submessage_arena);
    }
    
  } else {
    
  }
  information_ = information;
  // @@protoc_insertion_point(field_set_allocated:message.MessageDTO.information)
}

// .message.MessageType type = 5;
inline void MessageDTO::clear_type() {
  type_ = 0;
}
inline ::message::MessageType MessageDTO::_internal_type() const {
  return static_cast< ::message::MessageType >(type_);
}
inline ::message::MessageType MessageDTO::type() const {
  // @@protoc_insertion_point(field_get:message.MessageDTO.type)
  return _internal_type();
}
inline void MessageDTO::_internal_set_type(::message::MessageType value) {
  
  type_ = value;
}
inline void MessageDTO::set_type(::message::MessageType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:message.MessageDTO.type)
}

// string content = 6;
inline void MessageDTO::clear_content() {
  content_.ClearToEmpty();
}
inline const std::string& MessageDTO::content() const {
  // @@protoc_insertion_point(field_get:message.MessageDTO.content)
  return _internal_content();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void MessageDTO::set_content(ArgT0&& arg0, ArgT... args) {
 
 content_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:message.MessageDTO.content)
}
inline std::string* MessageDTO::mutable_content() {
  std::string* _s = _internal_mutable_content();
  // @@protoc_insertion_point(field_mutable:message.MessageDTO.content)
  return _s;
}
inline const std::string& MessageDTO::_internal_content() const {
  return content_.Get();
}
inline void MessageDTO::_internal_set_content(const std::string& value) {
  
  content_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* MessageDTO::_internal_mutable_content() {
  
  return content_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* MessageDTO::release_content() {
  // @@protoc_insertion_point(field_release:message.MessageDTO.content)
  return content_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void MessageDTO::set_allocated_content(std::string* content) {
  if (content != nullptr) {
    
  } else {
    
  }
  content_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), content,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (content_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    content_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:message.MessageDTO.content)
}

// .google.protobuf.Timestamp timestamp = 7;
inline bool MessageDTO::_internal_has_timestamp() const {
  return this != internal_default_instance() && timestamp_ != nullptr;
}
inline bool MessageDTO::has_timestamp() const {
  return _internal_has_timestamp();
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& MessageDTO::_internal_timestamp() const {
  const ::PROTOBUF_NAMESPACE_ID::Timestamp* p = timestamp_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Timestamp&>(
      ::PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& MessageDTO::timestamp() const {
  // @@protoc_insertion_point(field_get:message.MessageDTO.timestamp)
  return _internal_timestamp();
}
inline void MessageDTO::unsafe_arena_set_allocated_timestamp(
    ::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  timestamp_ = timestamp;
  if (timestamp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:message.MessageDTO.timestamp)
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* MessageDTO::release_timestamp() {
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = timestamp_;
  timestamp_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* MessageDTO::unsafe_arena_release_timestamp() {
  // @@protoc_insertion_point(field_release:message.MessageDTO.timestamp)
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = timestamp_;
  timestamp_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* MessageDTO::_internal_mutable_timestamp() {
  
  if (timestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaForAllocation());
    timestamp_ = p;
  }
  return timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* MessageDTO::mutable_timestamp() {
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _msg = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:message.MessageDTO.timestamp)
  return _msg;
}
inline void MessageDTO::set_allocated_timestamp(::PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  if (timestamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp));
    if (message_arena != submessage_arena) {
      timestamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    
  } else {
    
  }
  timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:message.MessageDTO.timestamp)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace message

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::message::MessageType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::message::MessageType>() {
  return ::message::MessageType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_message_5fdto_2eproto
