// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: state.proto

#include "grpc/state/state.pb.h"
#include "grpc/state/state.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* State_method_names[] = {
  "/State/CancelConn",
  "/State/SendMsg",
};

std::unique_ptr< State::Stub> State::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< State::Stub> stub(new State::Stub(channel, options));
  return stub;
}

State::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CancelConn_(State_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendMsg_(State_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status State::Stub::CancelConn(::grpc::ClientContext* context, const ::StateRequest& request, ::StateResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::StateRequest, ::StateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CancelConn_, context, request, response);
}

void State::Stub::async::CancelConn(::grpc::ClientContext* context, const ::StateRequest* request, ::StateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::StateRequest, ::StateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CancelConn_, context, request, response, std::move(f));
}

void State::Stub::async::CancelConn(::grpc::ClientContext* context, const ::StateRequest* request, ::StateResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CancelConn_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::StateResponse>* State::Stub::PrepareAsyncCancelConnRaw(::grpc::ClientContext* context, const ::StateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::StateResponse, ::StateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CancelConn_, context, request);
}

::grpc::ClientAsyncResponseReader< ::StateResponse>* State::Stub::AsyncCancelConnRaw(::grpc::ClientContext* context, const ::StateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCancelConnRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status State::Stub::SendMsg(::grpc::ClientContext* context, const ::StateRequest& request, ::StateResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::StateRequest, ::StateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendMsg_, context, request, response);
}

void State::Stub::async::SendMsg(::grpc::ClientContext* context, const ::StateRequest* request, ::StateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::StateRequest, ::StateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendMsg_, context, request, response, std::move(f));
}

void State::Stub::async::SendMsg(::grpc::ClientContext* context, const ::StateRequest* request, ::StateResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendMsg_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::StateResponse>* State::Stub::PrepareAsyncSendMsgRaw(::grpc::ClientContext* context, const ::StateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::StateResponse, ::StateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendMsg_, context, request);
}

::grpc::ClientAsyncResponseReader< ::StateResponse>* State::Stub::AsyncSendMsgRaw(::grpc::ClientContext* context, const ::StateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendMsgRaw(context, request, cq);
  result->StartCall();
  return result;
}

State::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      State_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< State::Service, ::StateRequest, ::StateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](State::Service* service,
             ::grpc::ServerContext* ctx,
             const ::StateRequest* req,
             ::StateResponse* resp) {
               return service->CancelConn(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      State_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< State::Service, ::StateRequest, ::StateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](State::Service* service,
             ::grpc::ServerContext* ctx,
             const ::StateRequest* req,
             ::StateResponse* resp) {
               return service->SendMsg(ctx, req, resp);
             }, this)));
}

State::Service::~Service() {
}

::grpc::Status State::Service::CancelConn(::grpc::ServerContext* context, const ::StateRequest* request, ::StateResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status State::Service::SendMsg(::grpc::ServerContext* context, const ::StateRequest* request, ::StateResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


