#pragma once
#include <stdio.h>
#include <string>
#include "srpc/rpc_define.h"
#include "gateway.pb.h"

namespace Gateway
{

/*
 * Server codes
 * Generated by SRPC
 */

class Service : public srpc::RPCService
{
public:
	// please implement these methods in server.cc

	virtual void DelConn(GatewayRequest *request, GatewayResponse *response,
					srpc::RPCContext *ctx) = 0;

	virtual void Push(GatewayRequest *request, GatewayResponse *response,
					srpc::RPCContext *ctx) = 0;

public:
	Service();
};

/*
 * Client codes
 * Generated by SRPC
 */

using DelConnDone = std::function<void (GatewayResponse *, srpc::RPCContext *)>;
using PushDone = std::function<void (GatewayResponse *, srpc::RPCContext *)>;

class SRPCClient : public srpc::SRPCClient
{
public:
	void DelConn(const GatewayRequest *req, DelConnDone done);
	void DelConn(const GatewayRequest *req, GatewayResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<GatewayResponse, srpc::RPCSyncContext>> async_DelConn(const GatewayRequest *req);

	void Push(const GatewayRequest *req, PushDone done);
	void Push(const GatewayRequest *req, GatewayResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<GatewayResponse, srpc::RPCSyncContext>> async_Push(const GatewayRequest *req);

public:
	SRPCClient(const char *host, unsigned short port);
	SRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCClientTask *create_DelConn_task(DelConnDone done);
	srpc::SRPCClientTask *create_Push_task(PushDone done);
};

class SRPCHttpClient : public srpc::SRPCHttpClient
{
public:
	void DelConn(const GatewayRequest *req, DelConnDone done);
	void DelConn(const GatewayRequest *req, GatewayResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<GatewayResponse, srpc::RPCSyncContext>> async_DelConn(const GatewayRequest *req);

	void Push(const GatewayRequest *req, PushDone done);
	void Push(const GatewayRequest *req, GatewayResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<GatewayResponse, srpc::RPCSyncContext>> async_Push(const GatewayRequest *req);

public:
	SRPCHttpClient(const char *host, unsigned short port);
	SRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCHttpClientTask *create_DelConn_task(DelConnDone done);
	srpc::SRPCHttpClientTask *create_Push_task(PushDone done);
};

class BRPCClient : public srpc::BRPCClient
{
public:
	void DelConn(const GatewayRequest *req, DelConnDone done);
	void DelConn(const GatewayRequest *req, GatewayResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<GatewayResponse, srpc::RPCSyncContext>> async_DelConn(const GatewayRequest *req);

	void Push(const GatewayRequest *req, PushDone done);
	void Push(const GatewayRequest *req, GatewayResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<GatewayResponse, srpc::RPCSyncContext>> async_Push(const GatewayRequest *req);

public:
	BRPCClient(const char *host, unsigned short port);
	BRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::BRPCClientTask *create_DelConn_task(DelConnDone done);
	srpc::BRPCClientTask *create_Push_task(PushDone done);
};

class TRPCClient : public srpc::TRPCClient
{
public:
	void DelConn(const GatewayRequest *req, DelConnDone done);
	void DelConn(const GatewayRequest *req, GatewayResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<GatewayResponse, srpc::RPCSyncContext>> async_DelConn(const GatewayRequest *req);

	void Push(const GatewayRequest *req, PushDone done);
	void Push(const GatewayRequest *req, GatewayResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<GatewayResponse, srpc::RPCSyncContext>> async_Push(const GatewayRequest *req);

public:
	TRPCClient(const char *host, unsigned short port);
	TRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCClientTask *create_DelConn_task(DelConnDone done);
	srpc::TRPCClientTask *create_Push_task(PushDone done);
};

class TRPCHttpClient : public srpc::TRPCHttpClient
{
public:
	void DelConn(const GatewayRequest *req, DelConnDone done);
	void DelConn(const GatewayRequest *req, GatewayResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<GatewayResponse, srpc::RPCSyncContext>> async_DelConn(const GatewayRequest *req);

	void Push(const GatewayRequest *req, PushDone done);
	void Push(const GatewayRequest *req, GatewayResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<GatewayResponse, srpc::RPCSyncContext>> async_Push(const GatewayRequest *req);

public:
	TRPCHttpClient(const char *host, unsigned short port);
	TRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCHttpClientTask *create_DelConn_task(DelConnDone done);
	srpc::TRPCHttpClientTask *create_Push_task(PushDone done);
};

///// implements detials /////

inline Service::Service(): srpc::RPCService("Gateway")
{
	this->srpc::RPCService::add_method("DelConn",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::DelConn);
		});

	this->srpc::RPCService::add_method("Push",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::Push);
		});
}

inline SRPCClient::SRPCClient(const char *host, unsigned short port):
	srpc::SRPCClient("Gateway")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCClient::init(&params);
}

inline SRPCClient::SRPCClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCClient("Gateway")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCClient::init(temp);
}

inline void SRPCClient::DelConn(const GatewayRequest *req, DelConnDone done)
{
	auto *task = this->create_rpc_client_task("DelConn", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::DelConn(const GatewayRequest *req, GatewayResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_DelConn(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<GatewayResponse, srpc::RPCSyncContext>> SRPCClient::async_DelConn(const GatewayRequest *req)
{
	using RESULT = std::pair<GatewayResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<GatewayResponse>("DelConn", srpc::RPCAsyncFutureCallback<GatewayResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCClient::Push(const GatewayRequest *req, PushDone done)
{
	auto *task = this->create_rpc_client_task("Push", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::Push(const GatewayRequest *req, GatewayResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Push(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<GatewayResponse, srpc::RPCSyncContext>> SRPCClient::async_Push(const GatewayRequest *req)
{
	using RESULT = std::pair<GatewayResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<GatewayResponse>("Push", srpc::RPCAsyncFutureCallback<GatewayResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCClientTask *SRPCClient::create_DelConn_task(DelConnDone done)
{
	return this->create_rpc_client_task("DelConn", std::move(done));
}

inline srpc::SRPCClientTask *SRPCClient::create_Push_task(PushDone done)
{
	return this->create_rpc_client_task("Push", std::move(done));
}

inline SRPCHttpClient::SRPCHttpClient(const char *host, unsigned short port):
	srpc::SRPCHttpClient("Gateway")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCHttpClient::init(&params);
}

inline SRPCHttpClient::SRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCHttpClient("Gateway")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCHttpClient::init(temp);
}

inline void SRPCHttpClient::DelConn(const GatewayRequest *req, DelConnDone done)
{
	auto *task = this->create_rpc_client_task("DelConn", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::DelConn(const GatewayRequest *req, GatewayResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_DelConn(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<GatewayResponse, srpc::RPCSyncContext>> SRPCHttpClient::async_DelConn(const GatewayRequest *req)
{
	using RESULT = std::pair<GatewayResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<GatewayResponse>("DelConn", srpc::RPCAsyncFutureCallback<GatewayResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCHttpClient::Push(const GatewayRequest *req, PushDone done)
{
	auto *task = this->create_rpc_client_task("Push", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::Push(const GatewayRequest *req, GatewayResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Push(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<GatewayResponse, srpc::RPCSyncContext>> SRPCHttpClient::async_Push(const GatewayRequest *req)
{
	using RESULT = std::pair<GatewayResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<GatewayResponse>("Push", srpc::RPCAsyncFutureCallback<GatewayResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_DelConn_task(DelConnDone done)
{
	return this->create_rpc_client_task("DelConn", std::move(done));
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_Push_task(PushDone done)
{
	return this->create_rpc_client_task("Push", std::move(done));
}

inline BRPCClient::BRPCClient(const char *host, unsigned short port):
	srpc::BRPCClient("Gateway")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::BRPCClient::init(&params);
}

inline BRPCClient::BRPCClient(const struct srpc::RPCClientParams *params):
	srpc::BRPCClient("Gateway")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::BRPCClient::init(temp);
}

inline void BRPCClient::DelConn(const GatewayRequest *req, DelConnDone done)
{
	auto *task = this->create_rpc_client_task("DelConn", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::DelConn(const GatewayRequest *req, GatewayResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_DelConn(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<GatewayResponse, srpc::RPCSyncContext>> BRPCClient::async_DelConn(const GatewayRequest *req)
{
	using RESULT = std::pair<GatewayResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<GatewayResponse>("DelConn", srpc::RPCAsyncFutureCallback<GatewayResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void BRPCClient::Push(const GatewayRequest *req, PushDone done)
{
	auto *task = this->create_rpc_client_task("Push", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::Push(const GatewayRequest *req, GatewayResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Push(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<GatewayResponse, srpc::RPCSyncContext>> BRPCClient::async_Push(const GatewayRequest *req)
{
	using RESULT = std::pair<GatewayResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<GatewayResponse>("Push", srpc::RPCAsyncFutureCallback<GatewayResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::BRPCClientTask *BRPCClient::create_DelConn_task(DelConnDone done)
{
	return this->create_rpc_client_task("DelConn", std::move(done));
}

inline srpc::BRPCClientTask *BRPCClient::create_Push_task(PushDone done)
{
	return this->create_rpc_client_task("Push", std::move(done));
}

inline TRPCClient::TRPCClient(const char *host, unsigned short port):
	srpc::TRPCClient("Gateway")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCClient::init(&params);
}

inline TRPCClient::TRPCClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCClient("Gateway")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCClient::init(temp);
}

inline void TRPCClient::DelConn(const GatewayRequest *req, DelConnDone done)
{
	auto *task = this->create_rpc_client_task("/Gateway/DelConn", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::DelConn(const GatewayRequest *req, GatewayResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_DelConn(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<GatewayResponse, srpc::RPCSyncContext>> TRPCClient::async_DelConn(const GatewayRequest *req)
{
	using RESULT = std::pair<GatewayResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<GatewayResponse>("/Gateway/DelConn", srpc::RPCAsyncFutureCallback<GatewayResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCClient::Push(const GatewayRequest *req, PushDone done)
{
	auto *task = this->create_rpc_client_task("/Gateway/Push", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::Push(const GatewayRequest *req, GatewayResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Push(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<GatewayResponse, srpc::RPCSyncContext>> TRPCClient::async_Push(const GatewayRequest *req)
{
	using RESULT = std::pair<GatewayResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<GatewayResponse>("/Gateway/Push", srpc::RPCAsyncFutureCallback<GatewayResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCClientTask *TRPCClient::create_DelConn_task(DelConnDone done)
{
	auto *task = this->create_rpc_client_task("/Gateway/DelConn", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCClientTask *TRPCClient::create_Push_task(PushDone done)
{
	auto *task = this->create_rpc_client_task("/Gateway/Push", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline TRPCHttpClient::TRPCHttpClient(const char *host, unsigned short port):
	srpc::TRPCHttpClient("Gateway")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCHttpClient::init(&params);
}

inline TRPCHttpClient::TRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCHttpClient("Gateway")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCHttpClient::init(temp);
}

inline void TRPCHttpClient::DelConn(const GatewayRequest *req, DelConnDone done)
{
	auto *task = this->create_rpc_client_task("DelConn", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::DelConn(const GatewayRequest *req, GatewayResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_DelConn(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<GatewayResponse, srpc::RPCSyncContext>> TRPCHttpClient::async_DelConn(const GatewayRequest *req)
{
	using RESULT = std::pair<GatewayResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<GatewayResponse>("DelConn", srpc::RPCAsyncFutureCallback<GatewayResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCHttpClient::Push(const GatewayRequest *req, PushDone done)
{
	auto *task = this->create_rpc_client_task("Push", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::Push(const GatewayRequest *req, GatewayResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Push(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<GatewayResponse, srpc::RPCSyncContext>> TRPCHttpClient::async_Push(const GatewayRequest *req)
{
	using RESULT = std::pair<GatewayResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<GatewayResponse>("Push", srpc::RPCAsyncFutureCallback<GatewayResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_DelConn_task(DelConnDone done)
{
	auto *task = this->create_rpc_client_task("DelConn", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_Push_task(PushDone done)
{
	auto *task = this->create_rpc_client_task("Push", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

} // end namespace Gateway

