// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: message_writer.proto

#include "common/grpc/domain/message/writer/message_writer.pb.h"
#include "common/grpc/domain/message/writer/message_writer.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace MessageDomain {

static const char* MessageWriter_method_names[] = {
  "/MessageDomain.MessageWriter/PushMessage",
};

std::unique_ptr< MessageWriter::Stub> MessageWriter::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MessageWriter::Stub> stub(new MessageWriter::Stub(channel, options));
  return stub;
}

MessageWriter::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_PushMessage_(MessageWriter_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MessageWriter::Stub::PushMessage(::grpc::ClientContext* context, const ::MessageDomain::PushMessageRequest& request, ::MessageDomain::PushMessageResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::MessageDomain::PushMessageRequest, ::MessageDomain::PushMessageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PushMessage_, context, request, response);
}

void MessageWriter::Stub::async::PushMessage(::grpc::ClientContext* context, const ::MessageDomain::PushMessageRequest* request, ::MessageDomain::PushMessageResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::MessageDomain::PushMessageRequest, ::MessageDomain::PushMessageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushMessage_, context, request, response, std::move(f));
}

void MessageWriter::Stub::async::PushMessage(::grpc::ClientContext* context, const ::MessageDomain::PushMessageRequest* request, ::MessageDomain::PushMessageResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushMessage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::MessageDomain::PushMessageResponse>* MessageWriter::Stub::PrepareAsyncPushMessageRaw(::grpc::ClientContext* context, const ::MessageDomain::PushMessageRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::MessageDomain::PushMessageResponse, ::MessageDomain::PushMessageRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PushMessage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::MessageDomain::PushMessageResponse>* MessageWriter::Stub::AsyncPushMessageRaw(::grpc::ClientContext* context, const ::MessageDomain::PushMessageRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPushMessageRaw(context, request, cq);
  result->StartCall();
  return result;
}

MessageWriter::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MessageWriter_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MessageWriter::Service, ::MessageDomain::PushMessageRequest, ::MessageDomain::PushMessageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MessageWriter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::MessageDomain::PushMessageRequest* req,
             ::MessageDomain::PushMessageResponse* resp) {
               return service->PushMessage(ctx, req, resp);
             }, this)));
}

MessageWriter::Service::~Service() {
}

::grpc::Status MessageWriter::Service::PushMessage(::grpc::ServerContext* context, const ::MessageDomain::PushMessageRequest* request, ::MessageDomain::PushMessageResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace MessageDomain

