// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: router.proto
#ifndef GRPC_router_2eproto__INCLUDED
#define GRPC_router_2eproto__INCLUDED

#include "router.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace Router {

class Router final {
 public:
  static constexpr char const* service_full_name() {
    return "Router.Router";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // 接入层调用
    virtual ::grpc::Status AddRecord(::grpc::ClientContext* context, const ::Router::AddRecordRequest& request, ::Router::AddRecordResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Router::AddRecordResponse>> AsyncAddRecord(::grpc::ClientContext* context, const ::Router::AddRecordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Router::AddRecordResponse>>(AsyncAddRecordRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Router::AddRecordResponse>> PrepareAsyncAddRecord(::grpc::ClientContext* context, const ::Router::AddRecordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Router::AddRecordResponse>>(PrepareAsyncAddRecordRaw(context, request, cq));
    }
    virtual ::grpc::Status DelRecord(::grpc::ClientContext* context, const ::Router::DelRecordRequest& request, ::Router::DelRecordResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Router::DelRecordResponse>> AsyncDelRecord(::grpc::ClientContext* context, const ::Router::DelRecordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Router::DelRecordResponse>>(AsyncDelRecordRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Router::DelRecordResponse>> PrepareAsyncDelRecord(::grpc::ClientContext* context, const ::Router::DelRecordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Router::DelRecordResponse>>(PrepareAsyncDelRecordRaw(context, request, cq));
    }
    // 供未来的state server改造成push server后调用
    virtual ::grpc::Status QueryRecord(::grpc::ClientContext* context, const ::Router::QueryRecordRequest& request, ::Router::QueryRecordResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Router::QueryRecordResponse>> AsyncQueryRecord(::grpc::ClientContext* context, const ::Router::QueryRecordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Router::QueryRecordResponse>>(AsyncQueryRecordRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Router::QueryRecordResponse>> PrepareAsyncQueryRecord(::grpc::ClientContext* context, const ::Router::QueryRecordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Router::QueryRecordResponse>>(PrepareAsyncQueryRecordRaw(context, request, cq));
    }
    // 让领域层的服务如writer server推送消息
    virtual ::grpc::Status PushMessage(::grpc::ClientContext* context, const ::Router::PushMessageRequest& request, ::Router::PushMessageResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Router::PushMessageResponse>> AsyncPushMessage(::grpc::ClientContext* context, const ::Router::PushMessageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Router::PushMessageResponse>>(AsyncPushMessageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Router::PushMessageResponse>> PrepareAsyncPushMessage(::grpc::ClientContext* context, const ::Router::PushMessageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Router::PushMessageResponse>>(PrepareAsyncPushMessageRaw(context, request, cq));
    }
    virtual ::grpc::Status FanoutMessage(::grpc::ClientContext* context, const ::Router::FanoutMessageRequest& request, ::Router::FanoutMessageResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Router::FanoutMessageResponse>> AsyncFanoutMessage(::grpc::ClientContext* context, const ::Router::FanoutMessageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Router::FanoutMessageResponse>>(AsyncFanoutMessageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Router::FanoutMessageResponse>> PrepareAsyncFanoutMessage(::grpc::ClientContext* context, const ::Router::FanoutMessageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Router::FanoutMessageResponse>>(PrepareAsyncFanoutMessageRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // 接入层调用
      virtual void AddRecord(::grpc::ClientContext* context, const ::Router::AddRecordRequest* request, ::Router::AddRecordResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AddRecord(::grpc::ClientContext* context, const ::Router::AddRecordRequest* request, ::Router::AddRecordResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void DelRecord(::grpc::ClientContext* context, const ::Router::DelRecordRequest* request, ::Router::DelRecordResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DelRecord(::grpc::ClientContext* context, const ::Router::DelRecordRequest* request, ::Router::DelRecordResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 供未来的state server改造成push server后调用
      virtual void QueryRecord(::grpc::ClientContext* context, const ::Router::QueryRecordRequest* request, ::Router::QueryRecordResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void QueryRecord(::grpc::ClientContext* context, const ::Router::QueryRecordRequest* request, ::Router::QueryRecordResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 让领域层的服务如writer server推送消息
      virtual void PushMessage(::grpc::ClientContext* context, const ::Router::PushMessageRequest* request, ::Router::PushMessageResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void PushMessage(::grpc::ClientContext* context, const ::Router::PushMessageRequest* request, ::Router::PushMessageResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void FanoutMessage(::grpc::ClientContext* context, const ::Router::FanoutMessageRequest* request, ::Router::FanoutMessageResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void FanoutMessage(::grpc::ClientContext* context, const ::Router::FanoutMessageRequest* request, ::Router::FanoutMessageResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Router::AddRecordResponse>* AsyncAddRecordRaw(::grpc::ClientContext* context, const ::Router::AddRecordRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Router::AddRecordResponse>* PrepareAsyncAddRecordRaw(::grpc::ClientContext* context, const ::Router::AddRecordRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Router::DelRecordResponse>* AsyncDelRecordRaw(::grpc::ClientContext* context, const ::Router::DelRecordRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Router::DelRecordResponse>* PrepareAsyncDelRecordRaw(::grpc::ClientContext* context, const ::Router::DelRecordRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Router::QueryRecordResponse>* AsyncQueryRecordRaw(::grpc::ClientContext* context, const ::Router::QueryRecordRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Router::QueryRecordResponse>* PrepareAsyncQueryRecordRaw(::grpc::ClientContext* context, const ::Router::QueryRecordRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Router::PushMessageResponse>* AsyncPushMessageRaw(::grpc::ClientContext* context, const ::Router::PushMessageRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Router::PushMessageResponse>* PrepareAsyncPushMessageRaw(::grpc::ClientContext* context, const ::Router::PushMessageRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Router::FanoutMessageResponse>* AsyncFanoutMessageRaw(::grpc::ClientContext* context, const ::Router::FanoutMessageRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Router::FanoutMessageResponse>* PrepareAsyncFanoutMessageRaw(::grpc::ClientContext* context, const ::Router::FanoutMessageRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status AddRecord(::grpc::ClientContext* context, const ::Router::AddRecordRequest& request, ::Router::AddRecordResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Router::AddRecordResponse>> AsyncAddRecord(::grpc::ClientContext* context, const ::Router::AddRecordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Router::AddRecordResponse>>(AsyncAddRecordRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Router::AddRecordResponse>> PrepareAsyncAddRecord(::grpc::ClientContext* context, const ::Router::AddRecordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Router::AddRecordResponse>>(PrepareAsyncAddRecordRaw(context, request, cq));
    }
    ::grpc::Status DelRecord(::grpc::ClientContext* context, const ::Router::DelRecordRequest& request, ::Router::DelRecordResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Router::DelRecordResponse>> AsyncDelRecord(::grpc::ClientContext* context, const ::Router::DelRecordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Router::DelRecordResponse>>(AsyncDelRecordRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Router::DelRecordResponse>> PrepareAsyncDelRecord(::grpc::ClientContext* context, const ::Router::DelRecordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Router::DelRecordResponse>>(PrepareAsyncDelRecordRaw(context, request, cq));
    }
    ::grpc::Status QueryRecord(::grpc::ClientContext* context, const ::Router::QueryRecordRequest& request, ::Router::QueryRecordResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Router::QueryRecordResponse>> AsyncQueryRecord(::grpc::ClientContext* context, const ::Router::QueryRecordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Router::QueryRecordResponse>>(AsyncQueryRecordRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Router::QueryRecordResponse>> PrepareAsyncQueryRecord(::grpc::ClientContext* context, const ::Router::QueryRecordRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Router::QueryRecordResponse>>(PrepareAsyncQueryRecordRaw(context, request, cq));
    }
    ::grpc::Status PushMessage(::grpc::ClientContext* context, const ::Router::PushMessageRequest& request, ::Router::PushMessageResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Router::PushMessageResponse>> AsyncPushMessage(::grpc::ClientContext* context, const ::Router::PushMessageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Router::PushMessageResponse>>(AsyncPushMessageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Router::PushMessageResponse>> PrepareAsyncPushMessage(::grpc::ClientContext* context, const ::Router::PushMessageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Router::PushMessageResponse>>(PrepareAsyncPushMessageRaw(context, request, cq));
    }
    ::grpc::Status FanoutMessage(::grpc::ClientContext* context, const ::Router::FanoutMessageRequest& request, ::Router::FanoutMessageResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Router::FanoutMessageResponse>> AsyncFanoutMessage(::grpc::ClientContext* context, const ::Router::FanoutMessageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Router::FanoutMessageResponse>>(AsyncFanoutMessageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Router::FanoutMessageResponse>> PrepareAsyncFanoutMessage(::grpc::ClientContext* context, const ::Router::FanoutMessageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Router::FanoutMessageResponse>>(PrepareAsyncFanoutMessageRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void AddRecord(::grpc::ClientContext* context, const ::Router::AddRecordRequest* request, ::Router::AddRecordResponse* response, std::function<void(::grpc::Status)>) override;
      void AddRecord(::grpc::ClientContext* context, const ::Router::AddRecordRequest* request, ::Router::AddRecordResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void DelRecord(::grpc::ClientContext* context, const ::Router::DelRecordRequest* request, ::Router::DelRecordResponse* response, std::function<void(::grpc::Status)>) override;
      void DelRecord(::grpc::ClientContext* context, const ::Router::DelRecordRequest* request, ::Router::DelRecordResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void QueryRecord(::grpc::ClientContext* context, const ::Router::QueryRecordRequest* request, ::Router::QueryRecordResponse* response, std::function<void(::grpc::Status)>) override;
      void QueryRecord(::grpc::ClientContext* context, const ::Router::QueryRecordRequest* request, ::Router::QueryRecordResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void PushMessage(::grpc::ClientContext* context, const ::Router::PushMessageRequest* request, ::Router::PushMessageResponse* response, std::function<void(::grpc::Status)>) override;
      void PushMessage(::grpc::ClientContext* context, const ::Router::PushMessageRequest* request, ::Router::PushMessageResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void FanoutMessage(::grpc::ClientContext* context, const ::Router::FanoutMessageRequest* request, ::Router::FanoutMessageResponse* response, std::function<void(::grpc::Status)>) override;
      void FanoutMessage(::grpc::ClientContext* context, const ::Router::FanoutMessageRequest* request, ::Router::FanoutMessageResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::Router::AddRecordResponse>* AsyncAddRecordRaw(::grpc::ClientContext* context, const ::Router::AddRecordRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Router::AddRecordResponse>* PrepareAsyncAddRecordRaw(::grpc::ClientContext* context, const ::Router::AddRecordRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Router::DelRecordResponse>* AsyncDelRecordRaw(::grpc::ClientContext* context, const ::Router::DelRecordRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Router::DelRecordResponse>* PrepareAsyncDelRecordRaw(::grpc::ClientContext* context, const ::Router::DelRecordRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Router::QueryRecordResponse>* AsyncQueryRecordRaw(::grpc::ClientContext* context, const ::Router::QueryRecordRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Router::QueryRecordResponse>* PrepareAsyncQueryRecordRaw(::grpc::ClientContext* context, const ::Router::QueryRecordRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Router::PushMessageResponse>* AsyncPushMessageRaw(::grpc::ClientContext* context, const ::Router::PushMessageRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Router::PushMessageResponse>* PrepareAsyncPushMessageRaw(::grpc::ClientContext* context, const ::Router::PushMessageRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Router::FanoutMessageResponse>* AsyncFanoutMessageRaw(::grpc::ClientContext* context, const ::Router::FanoutMessageRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Router::FanoutMessageResponse>* PrepareAsyncFanoutMessageRaw(::grpc::ClientContext* context, const ::Router::FanoutMessageRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_AddRecord_;
    const ::grpc::internal::RpcMethod rpcmethod_DelRecord_;
    const ::grpc::internal::RpcMethod rpcmethod_QueryRecord_;
    const ::grpc::internal::RpcMethod rpcmethod_PushMessage_;
    const ::grpc::internal::RpcMethod rpcmethod_FanoutMessage_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // 接入层调用
    virtual ::grpc::Status AddRecord(::grpc::ServerContext* context, const ::Router::AddRecordRequest* request, ::Router::AddRecordResponse* response);
    virtual ::grpc::Status DelRecord(::grpc::ServerContext* context, const ::Router::DelRecordRequest* request, ::Router::DelRecordResponse* response);
    // 供未来的state server改造成push server后调用
    virtual ::grpc::Status QueryRecord(::grpc::ServerContext* context, const ::Router::QueryRecordRequest* request, ::Router::QueryRecordResponse* response);
    // 让领域层的服务如writer server推送消息
    virtual ::grpc::Status PushMessage(::grpc::ServerContext* context, const ::Router::PushMessageRequest* request, ::Router::PushMessageResponse* response);
    virtual ::grpc::Status FanoutMessage(::grpc::ServerContext* context, const ::Router::FanoutMessageRequest* request, ::Router::FanoutMessageResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_AddRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AddRecord() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_AddRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddRecord(::grpc::ServerContext* /*context*/, const ::Router::AddRecordRequest* /*request*/, ::Router::AddRecordResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddRecord(::grpc::ServerContext* context, ::Router::AddRecordRequest* request, ::grpc::ServerAsyncResponseWriter< ::Router::AddRecordResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DelRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DelRecord() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_DelRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DelRecord(::grpc::ServerContext* /*context*/, const ::Router::DelRecordRequest* /*request*/, ::Router::DelRecordResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDelRecord(::grpc::ServerContext* context, ::Router::DelRecordRequest* request, ::grpc::ServerAsyncResponseWriter< ::Router::DelRecordResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_QueryRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_QueryRecord() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_QueryRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryRecord(::grpc::ServerContext* /*context*/, const ::Router::QueryRecordRequest* /*request*/, ::Router::QueryRecordResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestQueryRecord(::grpc::ServerContext* context, ::Router::QueryRecordRequest* request, ::grpc::ServerAsyncResponseWriter< ::Router::QueryRecordResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_PushMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PushMessage() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_PushMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushMessage(::grpc::ServerContext* /*context*/, const ::Router::PushMessageRequest* /*request*/, ::Router::PushMessageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPushMessage(::grpc::ServerContext* context, ::Router::PushMessageRequest* request, ::grpc::ServerAsyncResponseWriter< ::Router::PushMessageResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_FanoutMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_FanoutMessage() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_FanoutMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FanoutMessage(::grpc::ServerContext* /*context*/, const ::Router::FanoutMessageRequest* /*request*/, ::Router::FanoutMessageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFanoutMessage(::grpc::ServerContext* context, ::Router::FanoutMessageRequest* request, ::grpc::ServerAsyncResponseWriter< ::Router::FanoutMessageResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_AddRecord<WithAsyncMethod_DelRecord<WithAsyncMethod_QueryRecord<WithAsyncMethod_PushMessage<WithAsyncMethod_FanoutMessage<Service > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_AddRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AddRecord() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::Router::AddRecordRequest, ::Router::AddRecordResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Router::AddRecordRequest* request, ::Router::AddRecordResponse* response) { return this->AddRecord(context, request, response); }));}
    void SetMessageAllocatorFor_AddRecord(
        ::grpc::MessageAllocator< ::Router::AddRecordRequest, ::Router::AddRecordResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Router::AddRecordRequest, ::Router::AddRecordResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AddRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddRecord(::grpc::ServerContext* /*context*/, const ::Router::AddRecordRequest* /*request*/, ::Router::AddRecordResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AddRecord(
      ::grpc::CallbackServerContext* /*context*/, const ::Router::AddRecordRequest* /*request*/, ::Router::AddRecordResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DelRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DelRecord() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::Router::DelRecordRequest, ::Router::DelRecordResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Router::DelRecordRequest* request, ::Router::DelRecordResponse* response) { return this->DelRecord(context, request, response); }));}
    void SetMessageAllocatorFor_DelRecord(
        ::grpc::MessageAllocator< ::Router::DelRecordRequest, ::Router::DelRecordResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Router::DelRecordRequest, ::Router::DelRecordResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DelRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DelRecord(::grpc::ServerContext* /*context*/, const ::Router::DelRecordRequest* /*request*/, ::Router::DelRecordResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DelRecord(
      ::grpc::CallbackServerContext* /*context*/, const ::Router::DelRecordRequest* /*request*/, ::Router::DelRecordResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_QueryRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_QueryRecord() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::Router::QueryRecordRequest, ::Router::QueryRecordResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Router::QueryRecordRequest* request, ::Router::QueryRecordResponse* response) { return this->QueryRecord(context, request, response); }));}
    void SetMessageAllocatorFor_QueryRecord(
        ::grpc::MessageAllocator< ::Router::QueryRecordRequest, ::Router::QueryRecordResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Router::QueryRecordRequest, ::Router::QueryRecordResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_QueryRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryRecord(::grpc::ServerContext* /*context*/, const ::Router::QueryRecordRequest* /*request*/, ::Router::QueryRecordResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* QueryRecord(
      ::grpc::CallbackServerContext* /*context*/, const ::Router::QueryRecordRequest* /*request*/, ::Router::QueryRecordResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_PushMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_PushMessage() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::Router::PushMessageRequest, ::Router::PushMessageResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Router::PushMessageRequest* request, ::Router::PushMessageResponse* response) { return this->PushMessage(context, request, response); }));}
    void SetMessageAllocatorFor_PushMessage(
        ::grpc::MessageAllocator< ::Router::PushMessageRequest, ::Router::PushMessageResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Router::PushMessageRequest, ::Router::PushMessageResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_PushMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushMessage(::grpc::ServerContext* /*context*/, const ::Router::PushMessageRequest* /*request*/, ::Router::PushMessageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PushMessage(
      ::grpc::CallbackServerContext* /*context*/, const ::Router::PushMessageRequest* /*request*/, ::Router::PushMessageResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_FanoutMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_FanoutMessage() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::Router::FanoutMessageRequest, ::Router::FanoutMessageResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Router::FanoutMessageRequest* request, ::Router::FanoutMessageResponse* response) { return this->FanoutMessage(context, request, response); }));}
    void SetMessageAllocatorFor_FanoutMessage(
        ::grpc::MessageAllocator< ::Router::FanoutMessageRequest, ::Router::FanoutMessageResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Router::FanoutMessageRequest, ::Router::FanoutMessageResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_FanoutMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FanoutMessage(::grpc::ServerContext* /*context*/, const ::Router::FanoutMessageRequest* /*request*/, ::Router::FanoutMessageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FanoutMessage(
      ::grpc::CallbackServerContext* /*context*/, const ::Router::FanoutMessageRequest* /*request*/, ::Router::FanoutMessageResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_AddRecord<WithCallbackMethod_DelRecord<WithCallbackMethod_QueryRecord<WithCallbackMethod_PushMessage<WithCallbackMethod_FanoutMessage<Service > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_AddRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AddRecord() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_AddRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddRecord(::grpc::ServerContext* /*context*/, const ::Router::AddRecordRequest* /*request*/, ::Router::AddRecordResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DelRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DelRecord() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_DelRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DelRecord(::grpc::ServerContext* /*context*/, const ::Router::DelRecordRequest* /*request*/, ::Router::DelRecordResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_QueryRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_QueryRecord() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_QueryRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryRecord(::grpc::ServerContext* /*context*/, const ::Router::QueryRecordRequest* /*request*/, ::Router::QueryRecordResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_PushMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PushMessage() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_PushMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushMessage(::grpc::ServerContext* /*context*/, const ::Router::PushMessageRequest* /*request*/, ::Router::PushMessageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_FanoutMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_FanoutMessage() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_FanoutMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FanoutMessage(::grpc::ServerContext* /*context*/, const ::Router::FanoutMessageRequest* /*request*/, ::Router::FanoutMessageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_AddRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AddRecord() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_AddRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddRecord(::grpc::ServerContext* /*context*/, const ::Router::AddRecordRequest* /*request*/, ::Router::AddRecordResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddRecord(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DelRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DelRecord() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_DelRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DelRecord(::grpc::ServerContext* /*context*/, const ::Router::DelRecordRequest* /*request*/, ::Router::DelRecordResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDelRecord(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_QueryRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_QueryRecord() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_QueryRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryRecord(::grpc::ServerContext* /*context*/, const ::Router::QueryRecordRequest* /*request*/, ::Router::QueryRecordResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestQueryRecord(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_PushMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PushMessage() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_PushMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushMessage(::grpc::ServerContext* /*context*/, const ::Router::PushMessageRequest* /*request*/, ::Router::PushMessageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPushMessage(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_FanoutMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_FanoutMessage() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_FanoutMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FanoutMessage(::grpc::ServerContext* /*context*/, const ::Router::FanoutMessageRequest* /*request*/, ::Router::FanoutMessageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFanoutMessage(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AddRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AddRecord() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AddRecord(context, request, response); }));
    }
    ~WithRawCallbackMethod_AddRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddRecord(::grpc::ServerContext* /*context*/, const ::Router::AddRecordRequest* /*request*/, ::Router::AddRecordResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AddRecord(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DelRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DelRecord() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DelRecord(context, request, response); }));
    }
    ~WithRawCallbackMethod_DelRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DelRecord(::grpc::ServerContext* /*context*/, const ::Router::DelRecordRequest* /*request*/, ::Router::DelRecordResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DelRecord(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_QueryRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_QueryRecord() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->QueryRecord(context, request, response); }));
    }
    ~WithRawCallbackMethod_QueryRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryRecord(::grpc::ServerContext* /*context*/, const ::Router::QueryRecordRequest* /*request*/, ::Router::QueryRecordResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* QueryRecord(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_PushMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_PushMessage() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->PushMessage(context, request, response); }));
    }
    ~WithRawCallbackMethod_PushMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushMessage(::grpc::ServerContext* /*context*/, const ::Router::PushMessageRequest* /*request*/, ::Router::PushMessageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PushMessage(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_FanoutMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_FanoutMessage() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->FanoutMessage(context, request, response); }));
    }
    ~WithRawCallbackMethod_FanoutMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FanoutMessage(::grpc::ServerContext* /*context*/, const ::Router::FanoutMessageRequest* /*request*/, ::Router::FanoutMessageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FanoutMessage(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AddRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AddRecord() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Router::AddRecordRequest, ::Router::AddRecordResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Router::AddRecordRequest, ::Router::AddRecordResponse>* streamer) {
                       return this->StreamedAddRecord(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AddRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AddRecord(::grpc::ServerContext* /*context*/, const ::Router::AddRecordRequest* /*request*/, ::Router::AddRecordResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAddRecord(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Router::AddRecordRequest,::Router::AddRecordResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DelRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DelRecord() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Router::DelRecordRequest, ::Router::DelRecordResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Router::DelRecordRequest, ::Router::DelRecordResponse>* streamer) {
                       return this->StreamedDelRecord(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DelRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DelRecord(::grpc::ServerContext* /*context*/, const ::Router::DelRecordRequest* /*request*/, ::Router::DelRecordResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDelRecord(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Router::DelRecordRequest,::Router::DelRecordResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_QueryRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_QueryRecord() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Router::QueryRecordRequest, ::Router::QueryRecordResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Router::QueryRecordRequest, ::Router::QueryRecordResponse>* streamer) {
                       return this->StreamedQueryRecord(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_QueryRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status QueryRecord(::grpc::ServerContext* /*context*/, const ::Router::QueryRecordRequest* /*request*/, ::Router::QueryRecordResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedQueryRecord(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Router::QueryRecordRequest,::Router::QueryRecordResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PushMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_PushMessage() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Router::PushMessageRequest, ::Router::PushMessageResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Router::PushMessageRequest, ::Router::PushMessageResponse>* streamer) {
                       return this->StreamedPushMessage(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_PushMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PushMessage(::grpc::ServerContext* /*context*/, const ::Router::PushMessageRequest* /*request*/, ::Router::PushMessageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPushMessage(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Router::PushMessageRequest,::Router::PushMessageResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_FanoutMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_FanoutMessage() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Router::FanoutMessageRequest, ::Router::FanoutMessageResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Router::FanoutMessageRequest, ::Router::FanoutMessageResponse>* streamer) {
                       return this->StreamedFanoutMessage(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_FanoutMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status FanoutMessage(::grpc::ServerContext* /*context*/, const ::Router::FanoutMessageRequest* /*request*/, ::Router::FanoutMessageResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFanoutMessage(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Router::FanoutMessageRequest,::Router::FanoutMessageResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_AddRecord<WithStreamedUnaryMethod_DelRecord<WithStreamedUnaryMethod_QueryRecord<WithStreamedUnaryMethod_PushMessage<WithStreamedUnaryMethod_FanoutMessage<Service > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_AddRecord<WithStreamedUnaryMethod_DelRecord<WithStreamedUnaryMethod_QueryRecord<WithStreamedUnaryMethod_PushMessage<WithStreamedUnaryMethod_FanoutMessage<Service > > > > > StreamedService;
};

}  // namespace Router


#endif  // GRPC_router_2eproto__INCLUDED
