// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: router.proto

#include "common/grpc/router/router.pb.h"
#include "common/grpc/router/router.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace Router {

static const char* Router_method_names[] = {
  "/Router.Router/AddRecord",
  "/Router.Router/DelRecord",
  "/Router.Router/QueryRecord",
  "/Router.Router/PushMessage",
  "/Router.Router/FanoutMessage",
};

std::unique_ptr< Router::Stub> Router::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Router::Stub> stub(new Router::Stub(channel, options));
  return stub;
}

Router::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_AddRecord_(Router_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DelRecord_(Router_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_QueryRecord_(Router_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PushMessage_(Router_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_FanoutMessage_(Router_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Router::Stub::AddRecord(::grpc::ClientContext* context, const ::Router::AddRecordRequest& request, ::Router::AddRecordResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Router::AddRecordRequest, ::Router::AddRecordResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AddRecord_, context, request, response);
}

void Router::Stub::async::AddRecord(::grpc::ClientContext* context, const ::Router::AddRecordRequest* request, ::Router::AddRecordResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Router::AddRecordRequest, ::Router::AddRecordResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddRecord_, context, request, response, std::move(f));
}

void Router::Stub::async::AddRecord(::grpc::ClientContext* context, const ::Router::AddRecordRequest* request, ::Router::AddRecordResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddRecord_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Router::AddRecordResponse>* Router::Stub::PrepareAsyncAddRecordRaw(::grpc::ClientContext* context, const ::Router::AddRecordRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Router::AddRecordResponse, ::Router::AddRecordRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AddRecord_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Router::AddRecordResponse>* Router::Stub::AsyncAddRecordRaw(::grpc::ClientContext* context, const ::Router::AddRecordRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAddRecordRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Router::Stub::DelRecord(::grpc::ClientContext* context, const ::Router::DelRecordRequest& request, ::Router::DelRecordResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Router::DelRecordRequest, ::Router::DelRecordResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DelRecord_, context, request, response);
}

void Router::Stub::async::DelRecord(::grpc::ClientContext* context, const ::Router::DelRecordRequest* request, ::Router::DelRecordResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Router::DelRecordRequest, ::Router::DelRecordResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DelRecord_, context, request, response, std::move(f));
}

void Router::Stub::async::DelRecord(::grpc::ClientContext* context, const ::Router::DelRecordRequest* request, ::Router::DelRecordResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DelRecord_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Router::DelRecordResponse>* Router::Stub::PrepareAsyncDelRecordRaw(::grpc::ClientContext* context, const ::Router::DelRecordRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Router::DelRecordResponse, ::Router::DelRecordRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DelRecord_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Router::DelRecordResponse>* Router::Stub::AsyncDelRecordRaw(::grpc::ClientContext* context, const ::Router::DelRecordRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDelRecordRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Router::Stub::QueryRecord(::grpc::ClientContext* context, const ::Router::QueryRecordRequest& request, ::Router::QueryRecordResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Router::QueryRecordRequest, ::Router::QueryRecordResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_QueryRecord_, context, request, response);
}

void Router::Stub::async::QueryRecord(::grpc::ClientContext* context, const ::Router::QueryRecordRequest* request, ::Router::QueryRecordResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Router::QueryRecordRequest, ::Router::QueryRecordResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_QueryRecord_, context, request, response, std::move(f));
}

void Router::Stub::async::QueryRecord(::grpc::ClientContext* context, const ::Router::QueryRecordRequest* request, ::Router::QueryRecordResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_QueryRecord_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Router::QueryRecordResponse>* Router::Stub::PrepareAsyncQueryRecordRaw(::grpc::ClientContext* context, const ::Router::QueryRecordRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Router::QueryRecordResponse, ::Router::QueryRecordRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_QueryRecord_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Router::QueryRecordResponse>* Router::Stub::AsyncQueryRecordRaw(::grpc::ClientContext* context, const ::Router::QueryRecordRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncQueryRecordRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Router::Stub::PushMessage(::grpc::ClientContext* context, const ::Router::PushMessageRequest& request, ::Router::PushMessageResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Router::PushMessageRequest, ::Router::PushMessageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PushMessage_, context, request, response);
}

void Router::Stub::async::PushMessage(::grpc::ClientContext* context, const ::Router::PushMessageRequest* request, ::Router::PushMessageResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Router::PushMessageRequest, ::Router::PushMessageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushMessage_, context, request, response, std::move(f));
}

void Router::Stub::async::PushMessage(::grpc::ClientContext* context, const ::Router::PushMessageRequest* request, ::Router::PushMessageResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushMessage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Router::PushMessageResponse>* Router::Stub::PrepareAsyncPushMessageRaw(::grpc::ClientContext* context, const ::Router::PushMessageRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Router::PushMessageResponse, ::Router::PushMessageRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PushMessage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Router::PushMessageResponse>* Router::Stub::AsyncPushMessageRaw(::grpc::ClientContext* context, const ::Router::PushMessageRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPushMessageRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Router::Stub::FanoutMessage(::grpc::ClientContext* context, const ::Router::FanoutMessageRequest& request, ::Router::FanoutMessageResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Router::FanoutMessageRequest, ::Router::FanoutMessageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_FanoutMessage_, context, request, response);
}

void Router::Stub::async::FanoutMessage(::grpc::ClientContext* context, const ::Router::FanoutMessageRequest* request, ::Router::FanoutMessageResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Router::FanoutMessageRequest, ::Router::FanoutMessageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FanoutMessage_, context, request, response, std::move(f));
}

void Router::Stub::async::FanoutMessage(::grpc::ClientContext* context, const ::Router::FanoutMessageRequest* request, ::Router::FanoutMessageResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FanoutMessage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Router::FanoutMessageResponse>* Router::Stub::PrepareAsyncFanoutMessageRaw(::grpc::ClientContext* context, const ::Router::FanoutMessageRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Router::FanoutMessageResponse, ::Router::FanoutMessageRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_FanoutMessage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Router::FanoutMessageResponse>* Router::Stub::AsyncFanoutMessageRaw(::grpc::ClientContext* context, const ::Router::FanoutMessageRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFanoutMessageRaw(context, request, cq);
  result->StartCall();
  return result;
}

Router::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Router_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Router::Service, ::Router::AddRecordRequest, ::Router::AddRecordResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Router::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Router::AddRecordRequest* req,
             ::Router::AddRecordResponse* resp) {
               return service->AddRecord(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Router_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Router::Service, ::Router::DelRecordRequest, ::Router::DelRecordResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Router::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Router::DelRecordRequest* req,
             ::Router::DelRecordResponse* resp) {
               return service->DelRecord(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Router_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Router::Service, ::Router::QueryRecordRequest, ::Router::QueryRecordResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Router::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Router::QueryRecordRequest* req,
             ::Router::QueryRecordResponse* resp) {
               return service->QueryRecord(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Router_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Router::Service, ::Router::PushMessageRequest, ::Router::PushMessageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Router::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Router::PushMessageRequest* req,
             ::Router::PushMessageResponse* resp) {
               return service->PushMessage(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Router_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Router::Service, ::Router::FanoutMessageRequest, ::Router::FanoutMessageResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Router::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Router::FanoutMessageRequest* req,
             ::Router::FanoutMessageResponse* resp) {
               return service->FanoutMessage(ctx, req, resp);
             }, this)));
}

Router::Service::~Service() {
}

::grpc::Status Router::Service::AddRecord(::grpc::ServerContext* context, const ::Router::AddRecordRequest* request, ::Router::AddRecordResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Router::Service::DelRecord(::grpc::ServerContext* context, const ::Router::DelRecordRequest* request, ::Router::DelRecordResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Router::Service::QueryRecord(::grpc::ServerContext* context, const ::Router::QueryRecordRequest* request, ::Router::QueryRecordResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Router::Service::PushMessage(::grpc::ServerContext* context, const ::Router::PushMessageRequest* request, ::Router::PushMessageResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Router::Service::FanoutMessage(::grpc::ServerContext* context, const ::Router::FanoutMessageRequest* request, ::Router::FanoutMessageResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Router

